name: Action CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  upload-log:
    name: Upload to R2 - Log File (Multiple)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Create test file
        run: |
          mkdir tests/log
          echo Upload test - ${{ steps.date.outputs.date }} - File 1 > "tests/log/upload-${{ steps.date.outputs.date }}-file1"
          echo Upload test - ${{ steps.date.outputs.date }} - File 2 > "tests/log/upload-${{ steps.date.outputs.date }}-file2"
          mkdir tests/log2
          echo Upload test - ${{ steps.date.outputs.date }} - File 3 > "tests/log2/upload-${{ steps.date.outputs.date }}-file3"
          echo Upload test - ${{ steps.date.outputs.date }} - File 4 > "tests/log2/upload-${{ steps.date.outputs.date }}-file4"
      - name: Upload to R2
        uses: ./
        with:
          r2-account-id: ${{ secrets.TEST_R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.TEST_R2_AKID }}
          r2-secret-access-key: ${{ secrets.TEST_R2_SECRET_AK }}
          r2-bucket: ${{ secrets.TEST_R2_BUCKET }}
          source-dir: |
            tests/log/upload-${{ steps.date.outputs.date }}-file1
            tests/log/upload-${{ steps.date.outputs.date }}-file2
            tests/log2
            tests/dir
          destination-dir: r2-upload-action/test-logs